# Generated by Django 4.0.4 on 2022-06-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Std',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30, primary_key=True, serialize=False)),
                ('address', models.TextField(max_length=300)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
