# Generated by Django 4.0.4 on 2022-06-25 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('address', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=99)),
            ],
            options={
                'db_table': 'singer',
            },
        ),
        migrations.CreateModel(
            name='EmpQuali3',
            fields=[
                ('emp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='empapp.emp')),
                ('college', models.CharField(max_length=30)),
                ('hsc', models.IntegerField()),
                ('ssc', models.IntegerField()),
                ('grad', models.IntegerField()),
                ('description', models.TextField(max_length=400)),
            ],
            options={
                'db_table': 'emp_qualif3',
            },
            bases=('empapp.emp',),
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('duration', models.CharField(max_length=30)),
                ('singer', models.ManyToManyField(to='empapp.singer')),
            ],
            options={
                'db_table': 'songs',
            },
        ),
        migrations.CreateModel(
            name='EmpQuali2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=30)),
                ('hsc', models.IntegerField()),
                ('ssc', models.IntegerField()),
                ('grad', models.IntegerField()),
                ('description', models.TextField(max_length=400)),
                ('emp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='empapp.emp')),
            ],
            options={
                'db_table': 'emp_qualif2',
            },
        ),
        migrations.CreateModel(
            name='EmpQuali',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=30)),
                ('hsc', models.IntegerField()),
                ('ssc', models.IntegerField()),
                ('grad', models.IntegerField()),
                ('description', models.TextField(max_length=400)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empapp.emp')),
            ],
            options={
                'db_table': 'emp_qualif',
            },
        ),
    ]
